name: ga_eats_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/login/
    - assets/fonts/public-sans/

  fonts:
     - family: Public Sans
       fonts:
         - asset: assets/fonts/public-sans/PublicSans-Regular.ttf
         - asset: assets/fonts/public-sans/PublicSans-Italic.ttf
         - asset: assets/fonts/public-sans/PublicSans-Bold.ttf
         - asset: assets/fonts/public-sans/PublicSans-Thin.ttf
         - asset: assets/fonts/public-sans/PublicSans-SemiBold.ttf
         - asset: assets/fonts/public-sans/PublicSans-Medium.ttf
         - asset: assets/fonts/public-sans/PublicSans-MediumItalic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
